import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "next-themes"; // Import ThemeProvider from next-themes
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Let Kicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Add class attribute to enable class-based theme switching */}
      <body className={poppins.className}>
        <ThemeProvider attribute="class">
          {" "}
          {/* Wrap with ThemeProvider */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
