import type { Metadata } from "next"; 
import { Roboto_Condensed } from "next/font/google";
import { ThemeProvider } from "next-themes"; 
import "./globals.css";

const robotoCondensed = Roboto_Condensed({ subsets: ["latin"], weight: ["400", "700"] }); // Change to Roboto Condensed

export const metadata: Metadata = {
  title: "Let Kicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Add class attribute to enable class-based theme switching */}
      <body className={robotoCondensed.className}> {/* Update to robotoCondensed */}
        <ThemeProvider attribute="class">
          {" "}
          {/* Wrap with ThemeProvider */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
